import { useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import type { Term, TermGroup } from '@/domain/glossary';
import { TERMS, TERM_GROUPS, searchTerms } from '@/domain/glossary';
import { mn, pct } from '@/domain/format';
import { useScope } from '@/state/ScopeProvider';
import { Ic } from '@/components';

/**
 * The user manual, on GitHub.
 *
 * A link rather than a bundled copy: the manual is regenerated by `npm run
 * docs` and shipping a stale one inside the application would be worse than
 * linking the current one. It opens in a new tab so nobody loses the screen
 * they were on.
 */
const USER_MANUAL = 'https://github.com/mmasoodalam4-creator/Tazayud-PMO/blob/main/docs/USER_MANUAL.md';

const TABS = ['All terms', ...TERM_GROUPS, 'How to use this tool'] as const;

/** The six steps of the reporting cycle, in the order a person walks them. */
const STEPS: [string, string][] = [
  [
    'File the period',
    'The project manager enters the month’s actual cost, progress and programme — by hand, '
    + 'or by downloading PT_TEMPLATE, filling it and importing it. Importing fills the form; it '
    + 'never files the period.',
  ],
  [
    'Read the reconciliation panel',
    'The controls run against what was entered and show what does not agree, before anyone signs '
    + 'anything. A failing control is a refusal, not a warning — the write will not be accepted.',
  ],
  [
    'Validate',
    'The portfolio manager checks the filed period and either validates it or returns it with a '
    + 'reason. They cannot file it, and they cannot approve it.',
  ],
  [
    'Approve, which publishes it',
    'The director approves. Until then the figure reaches no dashboard; the director sees it as '
    + 'pending against the person holding it, without the numbers.',
  ],
  [
    'Record the certificate or claim',
    'Certified and paid move through the payment records, not through the period. Earned value and '
    + 'actual cost come from the period, which is why the period covering the work is filed first.',
  ],
  [
    'Read the position',
    'Dashboard, Cost and the registers all read the same approved data. If two screens disagree, '
    + 'one of them is a defect — report it rather than reconciling it by hand.',
  ],
];

/** Definitions, calculation methods, and how the figures connect. */
export function Glossary() {
  const [tab, setTab] = useState<string>('All terms');
  const [query, setQuery] = useState('');
  const { list, totals } = useScope();
  const asked = new URLSearchParams(useLocation().search).get('term') ?? '';

  // From `agg`, the one place a roll-up is computed — the screen whose whole
  // purpose is "the formula the code actually computes" was the one screen
  // summing seven of Aggregate's own fields by hand a second time.
  const { budget, control, afc, committed, ac: actual, certified, paid } = totals;

  const shown = useMemo<Term[]>(() => {
    const found = searchTerms(query);
    if (tab === 'All terms' || tab === 'How to use this tool') return found;
    return found.filter((t) => t.group === (tab as TermGroup));
  }, [query, tab]);

  return (
    <div className="fade-up">
      <div className="card" style={{ marginBottom: 16 }}>
        <div className="card-b">
          <div className="tabs">
            {TABS.map((t) => (
              <button key={t} type="button" className={`tab${tab === t ? ' active' : ''}`}
                onClick={() => setTab(t)}>{t}</button>
            ))}
          </div>

          {tab === 'How to use this tool' ? (
            <>
              <div className="gloss-steps">
                {STEPS.map(([title, body], i) => (
                  <div className="gloss-step" key={title}>
                    <div className="gloss-step-n">{`STEP ${String(i + 1).padStart(2, '0')}`}</div>
                    <h4>{title}</h4>
                    <p>{body}</p>
                  </div>
                ))}
              </div>

              {/*
                The full manual, here rather than as an icon in the top bar.
                It used to sit beside the notifications bell, one click from
                every screen — but a manual is something a person goes and
                reads once, not something they need permanently to hand, and
                the space in the top bar is better spent on signing out. This
                screen is already where somebody comes when they want to know
                how the system works.
              */}
              <div className="gloss-manual">
                <div>
                  <h4>The full user manual</h4>
                  <p className="muted">
                    Every screen, every role and every message the system can show you, written for
                    the people who use it rather than the people who built it.
                  </p>
                </div>
                <a className="btn btn-ghost" href={USER_MANUAL} target="_blank" rel="noopener noreferrer">
                  {Ic('documents', 15)}Open the user manual
                </a>
              </div>
            </>
          ) : (
            <>
              <div className="form-field full" style={{ maxWidth: 340, marginBottom: 14 }}>
                <label htmlFor="gloss-q">Search the glossary</label>
                <input id="gloss-q" value={query} placeholder="AFC, retention, earned value…"
                  onChange={(e) => setQuery(e.target.value)} />
              </div>
              {shown.length ? (
                <div className="gloss-grid">
                  {shown.map((t) => <TermCard key={t.id} term={t} asked={t.id === asked} />)}
                </div>
              ) : (
                <p className="muted" style={{ fontSize: 12.5 }}>
                  {`No term matches “${query}”. The glossary holds ${TERMS.length} terms.`}
                </p>
              )}
            </>
          )}
        </div>
      </div>

      {tab === 'How to use this tool' ? null : (
        <div className="card">
          <div className="card-h">
            <h3>The four budget figures, at this scope</h3>
            <span className="muted" style={{ fontSize: 11.5 }}>
              {`${list.length} development${list.length === 1 ? '' : 's'} · measured against the approved budget`}
            </span>
          </div>
          <div className="card-b">
            <div className="cmp">
              <Cmp name="Approved Budget" note="A permission. Set by the Board, moved only by a re-baseline."
                value={budget} of={budget} color="var(--navy)" />
              <Cmp name="Control Budget" note={`A discipline. ${mn(budget - control)} of contingency is held back.`}
                value={control} of={budget} color="var(--steel)" />
              <Cmp name="Anticipated Final Cost" note="A prediction. The only one that moves every period."
                value={afc} of={budget} color="var(--blue)" />
              <Cmp name="Committed Cost" note="An obligation. Signed, whether or not any work has been done."
                value={committed} of={budget} color="var(--green)" />
              <Cmp name="Actual Cost" note="Incurred for work performed to date."
                value={actual} of={budget} color="var(--muted)" />
            </div>

            <div className="gloss-gaps">
              <Gap label="Approved − AFC" value={mn(budget - afc)}
                note="Budget Variance. Favourable when positive." />
              <Gap label="Control − committed" value={mn(control - committed)}
                note="Uncommitted balance, free to award." />
              <Gap label="AFC − committed" value={mn(afc - committed)}
                note="Expected cost not yet placed under contract." />
              <Gap label="Certified − paid" value={mn(certified - paid)}
                note="Retention held, plus approvals awaiting transfer." />
            </div>

            <p className="muted" style={{ fontSize: 12, lineHeight: 1.7, marginTop: 14 }}>
              {`Every figure above is a cost to Tazayud, never a sale value. Certified stands at `}
              <b>{mn(certified)}</b>
              {` and paid at `}
              <b>{mn(paid)}</b>
              {` — `}
              <b>{pct(paid, committed, 1)}</b>
              {` of what has been committed.`}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

/** One term, with what it is, how it is calculated, and what it feeds. */
function TermCard({ term, asked }: { term: Term; asked: boolean }) {
  return (
    <div className={`gloss-term${asked ? ' asked' : ''}`} id={`term-${term.id}`}>
      <div className="gloss-term-h">
        <span className="gloss-term-n">{term.name}</span>
        {term.abbr ? <span className="gloss-term-ab">{term.abbr}</span> : null}
        <span className="pill b-grey" style={{ marginLeft: 'auto' }}>{term.group}</span>
      </div>
      <p>{term.definition}</p>
      {term.formula ? <div className="formula">{term.formula}</div> : null}
      {term.feeds ? (
        <div className="gloss-feeds">{Ic('chevR', 11)}<span>{term.feeds}</span></div>
      ) : null}
    </div>
  );
}

/** One bar in the budget comparison, always measured against the approved budget. */
function Cmp(
  { name, note, value, of, color }:
  { name: string; note: string; value: number; of: number; color: string },
) {
  const share = of > 0 ? Math.max(0, Math.min(100, (value / of) * 100)) : 0;
  return (
    <div className="cmp-row">
      <div className="cmp-name">
        <b>{name}</b>
        <span>{note}</span>
      </div>
      <div>
        <div className="cmp-track">
          <div className="cmp-fill" style={{ width: `${share}%`, background: color }}>{mn(value)}</div>
        </div>
      </div>
    </div>
  );
}

/** A difference between two of the figures, and what that difference is called. */
function Gap({ label, value, note }: { label: string; value: string; note: string }) {
  return (
    <div className="gloss-gap">
      <div className="gloss-gap-l">{label}</div>
      <div className="gloss-gap-v">{value}</div>
      <div className="gloss-gap-n">{note}</div>
    </div>
  );
}
