#!/usr/bin/env node
/**
 * Derive the blocks mark and the tab icon from the official Tazayud lockup.
 *
 *   node scripts/brand-crop.mjs
 *
 * The supplied artwork is one lockup: the dotted blocks in #66B3C9, and the
 * Arabic and Latin wordmarks in #0E223A. On the navy sidebar the wordmark half
 * is very nearly invisible, and the collapsed rail has no room for it anyway.
 *
 * Rather than redraw or recolour the owner's mark — which would make the
 * application's logo a thing somebody drew rather than the thing the brand is
 * — this takes the lockup's FIRST path, which is the blocks and nothing else,
 * and gives it a viewBox tightened to its own bounding box. The path data is
 * copied byte for byte. Re-run it after replacing the lockup file.
 *
 * The bounding box was measured in a real browser with getBBox(); it is
 * asserted below so a replaced lockup with different geometry fails here
 * rather than producing a crop with the mark half out of frame.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const LOCKUP = 'src/assets/brand/tazayud-lockup.svg';
const OUT = 'src/assets/brand/tazayud-blocks.svg';
const ICON = 'src/assets/brand/tazayud-favicon.svg';

// Measured in a real browser with getBBox(), and asserted below.
const BBOX = { x: 70.98, y: 0, w: 26.02, h: 31.78 };
const TILE = 40;

const svg = readFileSync(LOCKUP, 'utf8');
const paths = svg.match(/<path\b[\s\S]*?\/>/g) ?? [];
if (paths.length !== 2) {
  console.error(`\n${LOCKUP} has ${paths.length} paths; the lockup this was written for has two:`);
  console.error('  1. the blocks, #66B3C9   2. the Arabic and Latin wordmarks, #0E223A');
  console.error('Re-measure with getBBox() and update the viewBox below.\n');
  process.exit(1);
}
if (!paths[0].includes('#66B3C9')) {
  console.error(`\n${LOCKUP}: the first path is not the blocks (expected fill #66B3C9).\n`);
  process.exit(1);
}

writeFileSync(OUT, `<!-- The Tazayud blocks mark, cropped from the official lockup in
     tazayud-lockup.svg. Same path data, byte for byte: only the viewBox
     is tightened to the mark, so no artwork has been redrawn or
     recoloured. Generated by scripts/brand-crop.mjs. -->
<svg width="${BBOX.w}" height="${BBOX.h}" viewBox="${BBOX.x} ${BBOX.y} ${BBOX.w} ${BBOX.h}" fill="none"
     xmlns="http://www.w3.org/2000/svg">
${paths[0]}
</svg>
`);

// ---- the tab icon ----------------------------------------------------
//
// The same path, translated into a square navy tile. A favicon needs a
// GROUND: the mark is #66B3C9, which on a browser's own light tab strip has
// very little to hold on to, and the navy is the colour the application is
// already recognised by.
//
// A tile rather than a crop because a favicon is square in every context that
// uses one — tab, bookmark, history, the pinned-site grid — and letting the
// browser letterbox a 26x32 mark leaves it smaller than it needs to be.
const dx = (TILE - BBOX.w) / 2 - BBOX.x;
const dy = (TILE - BBOX.h) / 2 - BBOX.y;
writeFileSync(ICON, `<!-- The browser-tab icon: the same blocks path, byte for byte, centred
     on the navy ground the application is recognised by. Nothing redrawn,
     nothing recoloured. Generated by scripts/brand-crop.mjs.

     Set from src/assets/brand/index.ts rather than a <link> in index.html —
     vite-plugin-singlefile does not inline a link icon, and the portable
     deliverable must make no network request. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${TILE} ${TILE}" width="${TILE}" height="${TILE}">
<rect width="${TILE}" height="${TILE}" rx="8" fill="#0B2545"/>
<g transform="translate(${dx.toFixed(2)} ${dy.toFixed(2)})">
${paths[0]}
</g>
</svg>
`);

console.log(`\nbrand  ${OUT}\n       ${ICON}\n       both written from ${LOCKUP}\n`);
